# https://docs.github.com/en/actions

name: demo

on:
  pull_request:
    types: 
      - opened
    branches:
      - master

jobs:
  demo-job:
    runs-on: ubuntu-18.04
    steps:
        # checkout code on the branch
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          # cache npm dependencies
          # https://github.com/actions/setup-node#caching-packages-dependencies
          # cache: 'npm'
          cache: pnpm
          node-version: v17.2.0
          registry-url: "https://registry.npmjs.org/"
      - run: echo "READY!"
      - run: whereis pnpm
      - run: which pnpm
      - run: echo "DONE!"
      # - run: pnpm i -g pnpm
      # - run: pnpm install --frozen-lockfile
      # - run: pnpm run test
      # - run: pnpm run build
      # https://github.com/actions/checkout/issues/160
      # fetch all branches from remote
      # - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      # - run: git --no-pager diff origin/test/gha HEAD
      # - run: git --no-pager diff --name-status origin/test/gha HEAD | ./scripts/diffs.sh --verbose
      # - run: "echo result: \"$?\""
      - run: echo "DONE :)"

      # checkout

      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "HELLLLLLLLLLOOOOOOOOOOOOOOOOOO WORLD"
      # - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v2
      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "🍏 This job's status is ${{ job.status }}."